export type DefectGuide = {
  name: string;
  slug: string;
  description: string;
  causes: string[];
  checkFirst: string[];
  actions: string[];
  processAreas: string[];
  materialChecks: string[];
  whyThisHappens?: {
    simple: string;
    scientific: string;
    misconceptions: string[];
    ineffectiveFirstTries: string[];
    technicianFirstLooks: string[];
  };
  teachNewTechnician?: string[];
};

export const defectGuides: DefectGuide[] = [
  {
    name: "Short Shot",
    slug: "short-shot",
    description: "A part is only partially filled because the melt front freezes or loses pressure before the cavity is completely filled and packed.",
    causes: ["Insufficient shot size, injection pressure, injection speed, or pressure limit.", "Melt or mold temperature is too low for the resin and flow length.", "Blocked gates, runners, nozzles, vents, or restricted material flow paths."],
    checkFirst: ["Confirm cushion, transfer position, fill time, peak pressure, and whether the press is pressure-limited.", "Inspect feed, nozzle, gate, runner, and end-of-fill vents for restrictions."],
    actions: ["Increase shot size, transfer later, injection speed, or pressure limit in controlled steps.", "Raise melt or mold temperature within the approved material range.", "Clean or repair blocked flow paths, worn check rings, and restricted vents."],
    processAreas: ["Fill speed", "Shot size", "Transfer", "Venting", "Melt temperature"],
    materialChecks: ["Lot viscosity", "Drying status", "Regrind level", "Feed consistency"],
    whyThisHappens: {
      simple: "The cavity runs out of usable plastic before the part is full.",
      scientific: "The melt front loses heat or pressure before end-of-fill, so flow stops before packing can support the part.",
      misconceptions: ["It is always a shot-size problem.", "More heat fixes every short shot."],
      ineffectiveFirstTries: ["Adding random pack pressure before confirming the part fills.", "Raising every temperature zone at once."],
      technicianFirstLooks: ["Cushion, transfer, fill time, and pressure limit.", "Gate, runner, nozzle, feed, and end-of-fill vents."],
    },
    teachNewTechnician: ["A short shot is usually a fill problem first, not a pack problem.", "Save a sample and mark the short location and cavity.", "If the press hits pressure limit, it cannot push harder no matter what the speed setting says.", "One blocked gate or cold runner can look like a bad process."],
  },
  {
    name: "Flash",
    slug: "flash",
    description: "Thin excess plastic escapes at the parting line, vents, ejector pins, inserts, or shutoffs where the mold should remain sealed.",
    causes: ["Clamp force is too low or cavity pressure is too high.", "Worn, damaged, dirty, or misaligned mold shutoffs and parting-line surfaces.", "Excessive melt temperature, injection speed, pack pressure, or pack time."],
    checkFirst: ["Inspect parting line, vents, inserts, ejector areas, and mold alignment before changing pack.", "Verify clamp tonnage and compare peak pressure to the validated process."],
    actions: ["Clean or repair shutoffs, vent lands, inserts, and damaged parting-line areas.", "Reduce transfer, pack pressure, pack time, or injection speed in measured steps.", "Confirm fill-only parts separate fill pressure from pack pressure."],
    processAreas: ["Clamp", "Pack/hold", "Transfer", "Tooling shutoffs", "Venting"],
    materialChecks: ["Melt temperature", "Viscosity shift", "Moisture", "Wrong resin grade"],
    whyThisHappens: {
      simple: "Plastic is being squeezed into places where the mold should be closed tight.",
      scientific: "Cavity pressure exceeds the mold's ability to seal at the parting line, vents, pins, inserts, or shutoffs.",
      misconceptions: ["Flash always means clamp tonnage is too low.", "More pack pressure will make the edge cleaner."],
      ineffectiveFirstTries: ["Increasing pack or hold to fill small features.", "Ignoring dirty, damaged, or misaligned shutoffs."],
      technicianFirstLooks: ["Where the flash starts on the tool.", "Clamp setup, transfer point, peak pressure, and vent condition."],
    },
    teachNewTechnician: ["Flash is escaped plastic; find the escape path.", "Do not pack harder into a leaking mold.", "Compare the flashed area to vents, pins, inserts, and shutoffs.", "Clean steel and verify setup before chasing settings."],
  },
  {
    name: "Sink Marks",
    slug: "sink-marks",
    description: "Localized depressions appear when thick sections shrink after the outer skin has already solidified.",
    causes: ["Insufficient packing pressure, packing time, or gate seal control.", "Thick ribs, bosses, or wall sections cool slower than surrounding areas.", "Mold temperature, melt temperature, or cooling time is not balanced for the geometry."],
    checkFirst: ["Review part weight trend, cushion, pack pressure/time, and gate seal evidence.", "Check water flow around thick sections, cores, ribs, and bosses."],
    actions: ["Increase pack pressure and pack time until gate seal is confirmed.", "Improve cooling around thick sections and verify water flow.", "Review wall uniformity, rib thickness, and coring opportunities."],
    processAreas: ["Pack/hold", "Gate seal", "Cooling", "Part design", "Mold temperature"],
    materialChecks: ["Shrink rate", "Filler content", "Drying", "Lot change"],
    whyThisHappens: {
      simple: "Thick areas shrink inward after the surface has already hardened.",
      scientific: "Volumetric shrinkage in heavy sections is not replaced by effective packing before gate seal.",
      misconceptions: ["More cooling time always removes sink.", "Sink only comes from bad material."],
      ineffectiveFirstTries: ["Adding cooling time without checking gate seal.", "Raising pack pressure after the gate is already frozen."],
      technicianFirstLooks: ["Part weight, cushion, pack time, and gate-seal evidence.", "Ribs, bosses, and cooling near thick steel."],
    },
    teachNewTechnician: ["Sink follows thick plastic and weak packing.", "Part weight tells you if pack is getting into the part.", "Pack only helps while the gate is open.", "Look at ribs and bosses before blaming the operator."],
  },
  {
    name: "Burn Marks",
    slug: "burn-marks",
    description: "Dark or charred areas form where trapped gas overheats, material degrades, or melt sees excessive shear.",
    causes: ["Poor venting traps air or gas near end-of-fill locations.", "Injection speed, screw speed, or back pressure creates excessive shear heat.", "Residence time, barrel temperature, or contamination causes degradation."],
    checkFirst: ["Locate burn marks versus end-of-fill, weld lines, vents, gates, and cavity number.", "Inspect vents and purge condition for degraded material."],
    actions: ["Clean, inspect, or add venting at trapped gas locations.", "Reduce fill speed, screw speed, back pressure, or melt temperature when shear is excessive.", "Purge degraded material and reduce residence time."],
    processAreas: ["Venting", "Fill speed", "Shear", "Residence time", "Hot runner"],
    materialChecks: ["Degradation", "Contamination", "Drying temperature", "Purge compatibility"],
    whyThisHappens: {
      simple: "Air or gas gets trapped and scorches the plastic, or the plastic is overheated.",
      scientific: "Compressed gas, high shear, or long residence time raises local temperature enough to degrade polymer at the flow front.",
      misconceptions: ["Burns are always from barrel temperatures.", "Slowing the whole process is always safe."],
      ineffectiveFirstTries: ["Only lowering barrel heat while vents stay blocked.", "Making several speed and temperature changes together."],
      technicianFirstLooks: ["End-of-fill locations, vents, and cavity pattern.", "Fill speed profile, shear points, purge quality, and residence time."],
    },
    teachNewTechnician: ["Burns often show where trapped air had nowhere to go.", "Check vents before blaming material.", "A black spot at the end of fill is a clue, not a mystery.", "Purge evidence helps separate degraded material from trapped gas."],
  },
  {
    name: "Splay",
    slug: "splay",
    description: "Silver or streaky surface marks appear as moisture, volatiles, trapped air, or shear-degraded material reaches the surface.",
    causes: ["Material moisture is too high or drying conditions are incorrect.", "Air is entrained from poor feed, excessive decompression, or turbulent flow.", "Melt temperature, screw recovery, or fill speed causes degradation or shear."],
    checkFirst: ["Verify dryer temperature, dew point, drying time, and moisture readings.", "Check decompression, screw speed, back pressure, and feed throat stability."],
    actions: ["Dry or replace suspect resin and protect it from moisture pickup.", "Reduce suck-back, screw speed, back pressure, or aggressive fill speed.", "Purge contamination and clean material handling paths."],
    processAreas: ["Drying", "Screw recovery", "Decompression", "Fill speed", "Venting"],
    materialChecks: ["Moisture", "Volatiles", "Colorant compatibility", "Regrind cleanliness"],
    whyThisHappens: {
      simple: "Moisture, gas, or degraded material streaks across the part surface.",
      scientific: "Volatiles flash out of the melt or shear-degraded polymer reaches the surface during flow.",
      misconceptions: ["Splay is always wet resin.", "Turning up barrel heat will dry the material."],
      ineffectiveFirstTries: ["Raising heat before checking dryer performance.", "Adding more suck-back and pulling in more air."],
      technicianFirstLooks: ["Dryer temperature, dew point, time, and hopper condition.", "Screw speed, back pressure, decompression, and recent material changes."],
    },
    teachNewTechnician: ["Silver streaks usually mean something unwanted rode with the melt.", "Drying is time, temperature, airflow, and dew point—not just a hot hopper.", "Too much suck-back can pull air into the shot.", "Check material handling before changing every press setting."],
  },
  {
    name: "Warpage",
    slug: "warpage",
    description: "A molded part bends, twists, or bows when uneven shrinkage and residual stress pull the geometry out of shape.",
    causes: ["Uneven wall thickness, gate location, fiber orientation, or flow-induced stress.", "Unbalanced mold cooling or inconsistent coolant flow.", "Pack, hold, cooling, or ejection settings create nonuniform shrinkage."],
    checkFirst: ["Compare cooling water temperature and flow across cavities and mold halves.", "Measure dimensions at the same time after molding and review pack/cooling history."],
    actions: ["Balance mold temperatures and water circuits.", "Optimize pack pressure, hold time, cooling time, and ejection timing.", "Review gate location, wall thickness, ribs, and fiber direction."],
    processAreas: ["Cooling", "Pack/hold", "Ejection", "Mold temperature", "Part design"],
    materialChecks: ["Shrink rate", "Fiber orientation", "Filler content", "Lot change"],
    whyThisHappens: {
      simple: "Different areas shrink different amounts and pull the part out of shape.",
      scientific: "Uneven cooling, packing, orientation, or geometry creates nonuniform shrinkage and residual stress after ejection.",
      misconceptions: ["Warpage is fixed by just adding cooling time.", "Only the operator caused it."],
      ineffectiveFirstTries: ["Changing one mold-temperature zone without checking water flow.", "Judging parts before they cool the same amount."],
      technicianFirstLooks: ["Cooling flow and temperature by circuit and cavity.", "Pack balance, ejection temperature, wall thickness, and part handling."],
    },
    teachNewTechnician: ["Warp is a shrinkage balance problem.", "Measure parts the same way and at the same time after molding.", "Hot parts can bend after ejection if they are stacked or handled poorly.", "Cooling problems often hide as process problems."],
  },
  {
    name: "Jetting",
    slug: "jetting",
    description: "A snake-like stream or folded surface pattern appears when melt shoots through the gate without bonding smoothly to the cavity wall.",
    causes: ["Gate directs melt into open space instead of against a wall.", "Initial injection speed is too high for the gate and part geometry.", "Melt or mold temperature is too low for proper flow-front bonding."],
    checkFirst: ["Review gate style/location and whether the mark starts at the gate.", "Compare first-stage speed profile to the validated setup."],
    actions: ["Slow the initial injection speed or use a staged fill profile.", "Raise mold or melt temperature within the approved range.", "Review gate redesign, tab gate, or impingement options with tooling."],
    processAreas: ["Gate design", "Fill speed", "Melt temperature", "Mold temperature", "Flow front"],
    materialChecks: ["Viscosity", "Drying", "Cold material", "Colorant shear sensitivity"],
  },
  {
    name: "Weld Lines",
    slug: "weld-lines",
    description: "Visible or weak knit lines form where two melt fronts meet around holes, inserts, ribs, or multiple gates.",
    causes: ["Melt fronts are too cool or slow when they meet.", "Venting is poor at the meeting location.", "Gate location, wall thickness, or flow length creates a weak knit."],
    checkFirst: ["Map the line location against gates, holes, ribs, inserts, and end-of-fill vents.", "Check part strength requirements at the weld line."],
    actions: ["Increase melt temperature, mold temperature, or fill speed in controlled steps.", "Improve venting where melt fronts meet.", "Review gate location, flow leaders, overflow wells, or design changes."],
    processAreas: ["Fill speed", "Melt temperature", "Mold temperature", "Venting", "Gate design"],
    materialChecks: ["Moisture", "Contamination", "Filler orientation", "Regrind level"],
    whyThisHappens: {
      simple: "Two flow fronts meet but do not knit together strongly or cleanly.",
      scientific: "Melt fronts cool, lose pressure, or trap gas before polymer chains can interdiffuse across the meeting line.",
      misconceptions: ["A weld line is only cosmetic.", "More pack pressure always strengthens it."],
      ineffectiveFirstTries: ["Packing harder after a cold weak knit has formed.", "Ignoring venting where the fronts meet."],
      technicianFirstLooks: ["Gate, hole, insert, and flow-front map.", "Melt temperature, mold temperature, fill speed, and vents at the knit location."],
    },
    teachNewTechnician: ["A weld line is where flow fronts shake hands.", "If they meet cold or with trapped gas, the handshake is weak.", "Always ask whether the line is cosmetic or a strength risk.", "Location around holes and inserts matters."],
  },
  {
    name: "Flow Lines",
    slug: "flow-lines",
    description: "Rings, waves, or streaks show the path of a cooling or hesitating melt front on the part surface.",
    causes: ["Melt front is too cold or inconsistent during fill.", "Fill speed changes abruptly or hesitates.", "Wall thickness transitions, gates, or cold mold surfaces create visible flow history."],
    checkFirst: ["Check if lines follow flow from the gate and whether fill time is repeatable.", "Confirm mold temperature and water circuit stability."],
    actions: ["Increase mold or melt temperature within limits.", "Smooth the injection speed profile and avoid hesitation.", "Review gate size/location and wall transitions."],
    processAreas: ["Fill profile", "Mold temperature", "Melt temperature", "Gate design", "Wall thickness"],
    materialChecks: ["Viscosity shift", "Colorant dispersion", "Moisture", "Lot change"],
  },
  {
    name: "Voids",
    slug: "voids",
    description: "Internal pockets or bubbles form inside thick sections when shrinkage or trapped gas is not compensated by packing.",
    causes: ["Insufficient pack pressure or hold time before gate seal.", "Thick sections shrink internally as the outside freezes.", "Moisture or volatiles create gas pockets."],
    checkFirst: ["Section or weigh parts and review gate seal, cushion, pack pressure, and hold time.", "Verify drying and moisture condition before increasing pack."],
    actions: ["Increase effective packing until gate seal is proven.", "Improve cooling and core thick sections where possible.", "Dry or replace resin if gas voids are moisture-related."],
    processAreas: ["Pack/hold", "Gate seal", "Cooling", "Part design", "Drying"],
    materialChecks: ["Moisture", "Volatiles", "Shrink rate", "Regrind"],
    whyThisHappens: {
      simple: "A bubble or empty pocket forms inside the part instead of solid plastic.",
      scientific: "Thick-section shrinkage or trapped volatiles create internal cavities when packing cannot replace lost volume.",
      misconceptions: ["All voids are air bubbles from the mold.", "More cooling time is the first fix."],
      ineffectiveFirstTries: ["Cooling longer without proving pack and gate seal.", "Increasing pack before checking moisture or section thickness."],
      technicianFirstLooks: ["Cut parts, part weight, cushion, pack profile, and gate seal.", "Drying records and whether voids sit in thick sections."],
    },
    teachNewTechnician: ["Voids often hide until you cut the part or see a bubble in thick plastic.", "Shrink voids need effective pack while the gate is open.", "Gas voids point back to moisture, volatiles, or trapped air.", "Location inside a thick boss is an important clue."],
  },
  {
    name: "Brittleness",
    slug: "brittleness",
    description: "Parts crack, snap, or lose impact strength due to degradation, stress, contamination, weak weld lines, or poor packing.",
    causes: ["Wet or overheated resin has degraded.", "Too much regrind, wrong grade, or incompatible contamination is present.", "Weak weld lines, voids, molded-in stress, or underpacking reduce strength."],
    checkFirst: ["Confirm resin grade, drying records, moisture readings, lot, and regrind percentage.", "Compare break location to gates, weld lines, bosses, and high-stress features."],
    actions: ["Run properly dried virgin resin as a baseline.", "Reduce residence time, melt temperature, and regrind exposure.", "Restore pack/cooling settings and escalate for material testing if needed."],
    processAreas: ["Drying", "Residence time", "Pack/hold", "Cooling", "Weld lines"],
    materialChecks: ["Moisture degradation", "Regrind", "Wrong grade", "Contamination"],
  },
  {
    name: "Sticking",
    slug: "sticking",
    description: "Parts hang on the core, cavity, slides, or lifters instead of releasing cleanly during ejection.",
    causes: ["Insufficient draft, rough polish, undercuts, or damaged tooling.", "Part is too hot, overpacked, or shrinking tightly onto the core.", "Ejection system is unbalanced or moving too fast."],
    checkFirst: ["Identify exactly where the part hangs and inspect draft, polish, vents, slides, and ejectors.", "Check part temperature, cooling time, pack pressure, and ejection stroke/speed."],
    actions: ["Increase cooling or reduce overpacking where allowed.", "Balance ejection speed, stroke, and ejector return.", "Repair polish, add draft, or correct undercuts with tooling."],
    processAreas: ["Ejection", "Cooling", "Pack/hold", "Tool polish", "Draft"],
    materialChecks: ["Mold release use", "Shrink rate", "Additive bloom", "Resin grade"],
  },
  {
    name: "Drag Marks",
    slug: "drag-marks",
    description: "Scratches or scuffed streaks appear in the direction of draw when the part rubs during release.",
    causes: ["Insufficient draft, rough steel, burrs, or damaged texture.", "Part sticks from heat, overpacking, or shrink onto the core.", "Ejectors, slides, or lifters are misaligned."],
    checkFirst: ["Match mark direction to mold opening, slides, lifters, or ejection movement.", "Inspect steel condition and part release temperature."],
    actions: ["Polish or repair damaged steel and confirm adequate draft.", "Reduce sticking by adjusting pack/cooling within limits.", "Inspect and align slides, lifters, and ejector timing."],
    processAreas: ["Ejection", "Draft", "Tool surface", "Cooling", "Pack/hold"],
    materialChecks: ["Shrink rate", "Lubricants", "Mold release", "Filler abrasion"],
  },
  { name: "Ejector Pin Marks", slug: "ejector-pin-marks", description: "Raised, shiny, white, or depressed circles appear where ejector pins push the part out of the mold.", causes: ["Ejection force is high because the part is sticking or too hot.", "Ejector pins are uneven, damaged, undersized, or poorly located.", "Pack pressure or cooling imbalance creates stress at pin locations."], checkFirst: ["Inspect ejector pin height, condition, location, and witness marks.", "Check cooling time, part temperature, sticking, and pack pressure."], actions: ["Correct sticking and balance ejection speed/stroke.", "Increase cooling or reduce pack if the process is overpacked.", "Repair, polish, resize, or relocate ejector pins with tooling."], processAreas: ["Ejection", "Cooling", "Pack/hold", "Tooling", "Part design"], materialChecks: ["Shrink rate", "Mold release", "Filler content", "Stress whitening tendency"] },
  { name: "Gate Blush", slug: "gate-blush", description: "A hazy, white, or dull halo appears around the gate from shear, stress, cold slugging, or gate freeze effects.", causes: ["Excessive shear through a small or restrictive gate.", "High injection speed, cold material, or cold mold near the gate.", "Gate design or vestige creates localized stress."], checkFirst: ["Confirm blush starts at the gate and compare gate size, temperature, and first-stage speed.", "Check material drying and colorant compatibility."], actions: ["Reduce initial injection speed or gate shear.", "Raise melt/mold temperature within approved limits.", "Review gate size, land, cold slug, or vestige improvements."], processAreas: ["Gate design", "Fill speed", "Shear", "Melt temperature", "Mold temperature"], materialChecks: ["Moisture", "Colorant", "Stress whitening", "Cold pellets"] },
  { name: "Stringing", slug: "stringing", description: "Thin strands of plastic remain at the nozzle, sprue, hot-runner tip, or gate after mold open or part removal.", causes: ["Nozzle or hot-runner tip is too hot.", "Decompression, suck-back, or valve-gate timing is incorrect.", "Material has low viscosity, moisture, or excessive melt temperature."], checkFirst: ["Observe whether strings come from nozzle, sprue, gate, or hot-runner drops.", "Check nozzle/tip temperatures, decompression, and valve-gate timing."], actions: ["Lower nozzle or hot-tip temperature in small steps.", "Adjust decompression, sprue break, or valve-gate close timing.", "Verify drying and reduce melt temperature if material is too fluid."], processAreas: ["Nozzle", "Hot runner", "Decompression", "Melt temperature", "Gate timing"], materialChecks: ["Moisture", "Melt flow", "Additives", "Drying"] },
  { name: "Overpacking", slug: "overpacking", description: "The part is forced with too much hold pressure or time, causing high weight, flash, stress, sticking, or dimensional oversize.", causes: ["Pack pressure, pack time, or transfer position is too aggressive.", "Gate remains open longer than expected.", "Process compensates for another issue with excessive pressure."], checkFirst: ["Compare part weight, dimensions, cushion, transfer, pack pressure, and gate seal study.", "Look for flash, stress whitening, sticking, and high ejection force."], actions: ["Reduce pack pressure/time or transfer earlier in controlled steps.", "Use gate seal data to avoid packing after the gate is frozen.", "Fix tooling or fill restrictions instead of masking them with pack."], processAreas: ["Pack/hold", "Transfer", "Gate seal", "Clamp", "Ejection"], materialChecks: ["Shrink rate", "Viscosity", "Lot change", "Stress sensitivity"] },
  { name: "Underpacking", slug: "underpacking", description: "The part receives too little hold pressure or time, causing low weight, sink, voids, weak features, or dimensional undersize.", causes: ["Pack pressure/time is too low or transfer is too early.", "Gate freezes before pressure reaches thick sections.", "Cushion, check ring, or material feed is inconsistent."], checkFirst: ["Trend part weight, cushion, transfer, pack pressure/time, and gate seal evidence.", "Inspect for sinks, voids, weak bosses, and undersize dimensions."], actions: ["Increase pack pressure/time until part weight stabilizes at gate seal.", "Correct cushion or check-ring variation.", "Improve gate size, cooling, or thick-section design if pressure cannot reach the area."], processAreas: ["Pack/hold", "Gate seal", "Transfer", "Cushion", "Part weight"], materialChecks: ["Viscosity", "Drying", "Regrind", "Shrink rate"] },
  { name: "Dimensional Variation", slug: "dimensional-variation", description: "Critical dimensions drift or vary between shots, cavities, shifts, or measurement times.", causes: ["Cushion, transfer, pack, cooling, or mold temperature is unstable.", "Material lot, moisture, regrind, or shrink behavior changed.", "Measurement timing, fixture, or method is inconsistent."], checkFirst: ["Confirm the same gage, fixture, and time-after-molding are used.", "Trend cushion, fill time, peak pressure, part weight, water temperature, and cavity data."], actions: ["Stabilize process inputs before adjusting nominal dimensions.", "Balance cooling and packing across cavities.", "Verify material lot/drying and update process window if validated."], processAreas: ["Pack/hold", "Cooling", "Mold temperature", "Measurement", "Cavity balance"], materialChecks: ["Lot shrink", "Moisture", "Regrind", "Filler content"] },
  { name: "Color Streaks", slug: "color-streaks", description: "Visible streaks or swirls of different color show uneven colorant dispersion, contamination, moisture, or purge carryover.", causes: ["Color concentrate is poorly mixed or incompatible.", "Previous color/material remains in barrel, hot runner, loader, or grinder.", "Moisture, temperature, or shear causes additive separation."], checkFirst: ["Check colorant ratio, mixer/feed consistency, and recent color change history.", "Inspect purge, hopper, loader, grinder, and hot-runner drops."], actions: ["Purge and clean the complete material path.", "Verify letdown ratio and mixer operation.", "Adjust screw speed/back pressure only after material handling is correct."], processAreas: ["Material feed", "Mixing", "Screw recovery", "Hot runner", "Purging"], materialChecks: ["Colorant compatibility", "Contamination", "Moisture", "Regrind segregation"] },
  { name: "Gloss Variation", slug: "gloss-variation", description: "Part surfaces show inconsistent shine, dull patches, or cavity-to-cavity gloss differences.", causes: ["Mold temperature, cooling, or surface polish varies across the tool.", "Fill speed, pressure, or venting changes surface replication.", "Material moisture, additives, or colorant dispersion varies."], checkFirst: ["Compare gloss location to cavities, mold halves, water circuits, texture, and flow direction.", "Check mold temperature and fill speed repeatability."], actions: ["Balance mold temperature and cooling circuits.", "Restore fill speed/pressure needed for surface replication.", "Clean or repair tool surface and verify material/colorant condition."], processAreas: ["Mold temperature", "Cooling", "Fill speed", "Tool surface", "Venting"], materialChecks: ["Moisture", "Additive bloom", "Colorant", "Lot change"] },
  { name: "Contamination", slug: "contamination", description: "Foreign material, black specks, mixed resin, oil, dust, metal, or unexpected color appears in molded parts.", causes: ["Dirty loaders, grinders, hoses, hoppers, gaylords, or dryers.", "Wrong resin, colorant, purge compound, or regrind was introduced.", "Degraded polymer or tooling residue is breaking loose."], checkFirst: ["Quarantine suspect material and compare virgin resin, regrind, purge patties, and affected cavities.", "Inspect and clean the material path from storage through nozzle and hot runner."], actions: ["Purge and clean handling equipment, barrel, nozzle, and hot runner.", "Verify labels, lot traceability, regrind controls, and color-change procedure.", "Reduce degradation sources if contamination is burned resin."], processAreas: ["Material handling", "Purging", "Hot runner", "Residence time", "Housekeeping"], materialChecks: ["Wrong material", "Foreign debris", "Regrind", "Colorant", "Degradation"] },
];

export const troubleshootingHref = "/troubleshooting";
